# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "guyon.io"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: "Stories accompanied by photography + whatever else falls in"

# Tagline below the site title
tagline: "Stories accompanied by photography + whatever else falls in"

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://guyon.io/"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Pages
  url: /pages/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
# disqus:

# Author information - author info at the bottom of the post
author_name: "Guyon"
author_bio: "Follower of Jesus, gearhead, photographer, and software engineer"
author_url: "https://guyon.io/"
author_location: "Richmond, Virginia"
author_image: authorimage.jpg

# Footer ad banner
banner_url: "https://guyon.io/"
banner_image: banner.jpg

# Footer newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "gooyawn"
#facebook_username: "username"
#googleplus_username: "+username"
#github_username: "gkubed"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
flickr_username: "gkubed"
instagram_username: "guyon_86"
#pinterest_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 7
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
